"""Rename group_id to group_room_number

Revision ID: b198395bae8d
Revises: 52fc49033d3d
Create Date: 2024-05-31 05:20:30.338475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b198395bae8d'
down_revision = '52fc49033d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_room_number', sa.String(length=20), nullable=False))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.VARCHAR(length=20), server_default=sa.text("'default_group'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('group_room_number')

    # ### end Alembic commands ###
